-- MySQL Script generated by MySQL Workbench
-- Fri May 29 13:19:54 2020
-- Model: StautRH - API   Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stautrh_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stautrh_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stautrh_api` DEFAULT CHARACTER SET utf8 ;
USE `stautrh_api` ;

-- -----------------------------------------------------
-- Table `stautrh_api`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stautrh_api`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `deleted` VARCHAR(1) NOT NULL DEFAULT '0',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `stautrh_api`.`drinked_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stautrh_api`.`drinked_list` (
  `id_drinked` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `quantity_ml` FLOAT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_drinked`),
  INDEX `id_user_idx` (`id_user` ASC),
  CONSTRAINT `id_user_drinked`
    FOREIGN KEY (`id_user`)
    REFERENCES `stautrh_api`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stautrh_api`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stautrh_api`.`tokens` (
  `id_token` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `token` VARCHAR(256) NOT NULL,
  `valid_until` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `invalid` VARCHAR(1) NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_token`),
  INDEX `id_user_idx` (`id_user` ASC),
  CONSTRAINT `id_user_token`
    FOREIGN KEY (`id_user`)
    REFERENCES `stautrh_api`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


--
-- Extraindo dados da tabela `users`
--

INSERT INTO `users` (`id_user`, `name`, `email`, `password`, `deleted`, `create_time`) VALUES
(1, 'Állan Lima', 'allan.aws@hotmail.com', '173af653133d964edfc16cafe0aba33c8f500a07f3ba3f81943916910c257705', '0', '2020-05-29 16:41:44'),
(2, 'Jaqueline Messina', 'jaqueline.messina@stautrh.com.br', '173af653133d964edfc16cafe0aba33c8f500a07f3ba3f81943916910c257705', '0', '2020-05-29 16:41:44'),
(3, 'Sandra Scaciotti', 'sandra@stautrh.com.br', '173af653133d964edfc16cafe0aba33c8f500a07f3ba3f81943916910c257705', '0', '2020-05-29 16:42:18');

INSERT INTO `drinked_list` (`id_drinked`, `id_user`, `quantity_ml`, `create_time`) VALUES
(1, 1, 200, '2020-05-29 18:22:36'),
(2, 1, 300, '2020-05-29 18:22:36'),
(3, 1, 320, '2020-05-29 18:22:36'),
(4, 1, 600, '2020-05-29 18:22:36'),
(5, 2, 460, '2020-05-29 18:22:36');